// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aynzfbpcnzsxtxnexvnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bnpmYnBjbnpzeHR4bmV4dm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjM3NjAzMDIsImV4cCI6MjAzOTMzNjMwMn0.Wcwc0bQBeWQPQfbX76j8AXjWbMsIJDH3NI9OPeczRLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);